INSERT INTO clientes (nombre, direccion, create_at) VALUES('Edwin Hernández',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Valeria Roque',  'San Juan Tepezontes', '2018-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Oscar Hernández',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Emerson Mendez',  'San Juan Tepezontes', '2018-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Edwin Hernández',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Valeria Roque',  'San Juan Tepezontes', '2018-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('David Roque',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Andrea Sánchez',  'San Juan Tepezontes', '2018-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Luis Calixto',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Andrew Holmos',  'San Juan Tepezontes', '2018-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Edwin Hernández',  'San Martín', '2017-08-01');
INSERT INTO clientes (nombre, direccion, create_at) VALUES('Valeria Roque',  'San Juan Tepezontes', '2018-08-01');